### ISSUE TITLE
Evaluate using additional optimizations like LTO and PGO

### ISSUE THREAD

**Issue by zamazan4ik** [IncognitoBin/IncognitoBin#8]
Hi!

I just read the [post](https://www.reddit.com/r/rust/comments/1ggnmn7/incognitobin_a_fast_opensource_scalable/) on Reddit about IncognitoBin. Since one of the key features of the project is "Scalable and fast", I decided to propose several improvement ideas for IncognitoBin. I created the Issue just because Discussions are disabled for the repo now.

### Link-Time Optimization (LTO)

I noticed that in the `Cargo.toml` file Link-Time Optimization (LTO) for the project is not enabled. I suggest switching it on since it will reduce the binary size (always a good thing to have) and will likely improve the application's performance a bit.

I suggest enabling LTO only for the Release builds so as not to sacrifice the developers' experience while working on the project since LTO consumes an additional amount of time to finish the compilation routine. If you think that a regular Release build should not be affected by such a change as well, then I suggest adding an additional `dist` or `release-lto` profile where additionally to regular `release` optimizations LTO will also be added. Such a change simplifies life for maintainers and others interested in the project persons who want to build the most performant version of the application. Using ThinLTO should also help to reduce the build-time overhead with LTO. E.g., check `cargo-outdated` Release [profile](https://github.com/kbknapp/cargo-outdated/blob/master/Cargo.toml#L48).

Basically, it can be enabled with the following lines to both `Cargo.toml`:

```
[profile.release]
lto = true
```

I have made quick tests (Fedora 41) by adding `lto = true` to the Release profile. The binary size reduction is the following:
* Server: from 13 Mib to 8.6 Mib
* Worker: from 5.2 Mib to 3.9 Mib

### Profile-Guided Optimization (PGO) and Post-Link Optimization (PLO)

According to my [benchmarks](https://github.com/zamazan4ik/awesome-pgo), PGO measurably helps to optimize various applications (its CPU efficiency more precisely) like regular backends (like IncognitoBin's `Server` and `Worker` projects) and databases since ScyllaDB and Redis are used (for both of them PGO benchmarks are available in the "awesome-pgo" repo). That's why I think applying PGO (and a similar PLO technique via [LLVM BOLT](https://github.com/llvm/llvm-project/blob/main/bolt/README.md)) could help to optimize IncognitoBin further. You may be interested in applying PGO and PLO to 3rd party projects used by IncognitoBin on the server side to improve response time, reduce CPU usage, and prepare for higher workloads (if you plan to do so, ofc).

Thank you.

**Comment by X-SP33D** [comment]
**Hi!**

Thank you so much for your detailed feedback and for bringing this to my attention! I’ve just enabled **Discussions** for the repository, so future ideas and suggestions can be shared there as well.

I really appreciate your suggestion on enabling **Link-Time Optimization (LTO)**. I’ve just made updates, and the next release will include LTO to enhance performance. I’m also excited to share that enabling LTO has already reduced the binary sizes significantly! Here’s a summary of the improvements:

- **Windows**
  - Server binary: from 10,272 KB to 8,506 KB
  - Worker binary: from 4,449 KB to 3,968 KB
- **Ubuntu**
  - Server binary: from 12,919 KB to 9,002 KB
  - Worker binary: from 5,414 KB to 4,034 KB

As for **Profile-Guided Optimization (PGO)** and **Post-Link Optimization (PLO)**, I agree they sound promising for further optimization. I’ll need to educate myself more on these techniques before implementing them, but they’re definitely on my radar, especially given the potential to enhance CPU efficiency and scalability.

Thanks again for your suggestions and for helping to make IncognitoBin even better!

**Comment by X-SP33D** [comment]
#13  [Quick Login Feature & Optimize Binary Size for Worker and Server
](https://github.com/IncognitoBin/IncognitoBin/pull/13)
Hi zamazan4ik,

I wanted to let you know that I’ve implemented Link-Time Optimization (LTO) as you recommended. The changes have already been pushed, and I'm seeing a noticeable improvement in performance. Thank you again for the suggestion and for your valuable guidance
